# appspec.yml

version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app/step2/zip # 프로젝트 이름
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: ubuntu
    - location: script/run_new_was.sh
      timeout: 180
      runas: ubuntu
    - location: script/health_check.sh
      timeout: 180
      runas: ubuntu
    - location: script/switch.sh
      timeout: 180
      runas: ubuntu